"""remove_denoise_status

Revision ID: e1f0d63b5e43
Revises: f3b91cfa0bef
Create Date: 2025-12-11 17:54:19.179248
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1f0d63b5e43'
down_revision: Union[str, None] = 'f3b91cfa0bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'denoise_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('denoise_status', postgresql.ENUM('NOT_NEEDED', 'FLAGGED', 'QUEUED', 'PROCESSED', name='denoisestatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
